name: Build And Release

on:
  workflow_dispatch:
      

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'wanweird/HeadSteal'
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-disabled: true

      - name: Build file
        run: gradle shadowJar

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/plugin.jar

      - name: Write Version
        uses: actions/upload-artifact@v3
        with:
          name: plugin-ver
          path: version
  release:
    permissions:
      contents: write

    name: Release Plugin
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download Plugin
        uses: actions/download-artifact@v3
        with:
          name: plugin

      - name: Check Version
        uses: actions/download-artifact@v3
        with:
          name: plugin-ver

      - name: Set version as ENV
        run: cat version >> $GITHUB_ENV

      - name: Rename File
        run: mv plugin.jar ${{ github.event.repository.name }}-${{ env.PLUGIN_VERSION }}.jar

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          draft: true
          body: ${{ env.PLUGIN_VERSION }}-${{ github.run_number }}+${{ github.run_attempt }}
          name: ${{ github.event.repository.name }} v${{ env.PLUGIN_VERSION }}-${{ github.run_number }}
          tag_name: ${{ env.PLUGIN_VERSION }}-${{ github.run_number }}+${{ github.run_attempt }}
          files: ${{ github.event.repository.name }}-${{ env.PLUGIN_VERSION }}.jar
